### PR TITLE
Allow `!default` annotation

### PR DESCRIPTION
**Pull request by Hyzual**
This fixes stylelint-scss/stylelint-config-recommended-scss#131

### CODE REVIEW

**Review by jnoordsij — APPROVED** [review]

**Comment by kristerkari** [comment]
Hmm.. looks like the tests are broken, maybe on master too. Need to have a look at that.

**Comment by jnoordsij** [comment]
Seeing messages like "Unknown rule annotation-no-unknown", which suggest #117 might be required first.

Side note: you might want to consider replacing tests on Node v12 with tests on Node v18.

**Comment by jnoordsij** [comment]
@Hyzual I made https://github.com/jnoordsij/stylelint-config-recommended-scss/tree/allow-default-annotation to do this. Feel free to cherry-pick it and finish this PR.

**Comment by jnoordsij** [comment]
Note that in https://github.com/stylelint-scss/stylelint-scss/issues/666 there's a request for a custom scss version of this rule. If that lands, it would allow for more customised handling and would remove the need for manual configuration.

**Comment by Hyzual** [comment]
@jnoordsij Thanks! I've pulled your branch and force-pushed this PR
@kristerkari the PR is rebased on top of master, @jnoordsij added examples to the `valid.scss` file :)

**Pull request merged**
