### PR TITLE
Replace deprecated rule

### LINKED ISSUE #251: Deprecation warning with stylelint-scss 5.3.0 (5.2.1+?)
Hello,

I'm getting a deprecation warning after upgrading ~stylelint-scss to 5.3.0~ something and *I think* (apologies if this is not the case, I'm not a javascript developer) it may be triggered by this library, which I'm using as a dependency of `stylelint-config-twbs-bootstrap` and `stylelint-config-standard-scss`

https://github.com/stylelint-scss/stylelint-config-recommended-scss/blob/b976432477b8cf955d728c2236b05bac88abe943/index.js#L23

```
Deprecation warnings:
 - The "scss/at-import-no-partial-leading-underscore" rule is deprecated.
 - 'at-import-no-partial-leading-underscore' has been deprecated, and will be removed in '6.0'. Use 'load-no-partial-leading-underscore' instead. See: https://github.com/stylelint-scss/stylelint-scss/blob/v5.2.1/src/rules/at-import-no-partial-leading-underscore/README.md
```

Ref: https://github.com/diowa/ruby3-rails7-bootstrap-heroku/actions/runs/6688272782/job/18170091224#step:6:13

Update: I'm seeing this deprecation message also on 5.2.1.

```
Deprecation warnings:
 - The "scss/at-import-no-partial-leading-underscore" rule is deprecated.
 - 'at-import-no-partial-leading-underscore' has been deprecated, and will be removed in '6.0'. Use 'load-no-partial-leading-underscore' instead. See: https://github.com/stylelint-scss/stylelint-scss/blob/v5.2.1/src/rules/at-import-no-partial-leading-underscore/README.md
```

### PR DESCRIPTION
**Pull request by XhmikosR**
Replace `scss/at-import-no-partial-leading-underscore` with `scss/at-import-no-partial-leading-underscore` introduced with stylelint-scss 5.3.0

Fixes #251

### CODE REVIEW

**Comment by XhmikosR** [comment]
@kristerkari could you cut a new minor/patch release please?

**Comment by kristerkari** [comment]
sure

**Comment by XhmikosR** [comment]
@kristerkari thanks! Can you also cut a new minor/patch release in https://github.com/stylelint-scss/stylelint-config-standard-scss please?

**Comment by XhmikosR** [comment]
BTW we should have updated known-css-properties in stylelint-scss so that it's deduped, but next time.

**Comment by kristerkari** [comment]
@XhmikosR sure, I'll release it too

**Pull request merged**
