### PR TITLE
Replace deprecated rule

### PR DESCRIPTION
**Pull request by kristerkari**
Replace `scss/at-import-partial-extension` with `scss/load-partial-extension` introduced with `stylelint-scss` 6.4.0

### CODE REVIEW

**Comment by XhmikosR** [comment]
@kristerkari any chance you could cut a new patch release with this fix?

**Comment by kristerkari** [comment]
@XhmikosR it should already be included in the latest version. Is it not?

**Comment by XhmikosR** [comment]
Yup, sorry for the noise, I edited my previous message. My lockfile wasn't updated for some reason (dependabot is buggy many times...)

**Comment by kristerkari** [comment]
No worries! Just let me know if you need anything else 🙂

**Pull request merged**
